<<<<<<< HEAD
<<<<<<< HEAD
github: [marco76tv, laraxot]
=======
github: laraxot
>>>>>>> c0f6f7d0d3 (Squashed 'laravel/Modules/Cms/' content from commit 8c1c023bf9)
=======
github: [marco76tv, laraxot]
>>>>>>> d14059a494 (Squashed 'laravel/Modules/Rating/' content from commit d80b37240f)
