blank_issues_enabled: false
contact_links:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    - name: Ask a question
      url: https://github.com/laraxot/module_xot/discussions/new?category=q-a
      about: Ask the community for help
    - name: Request a feature
      url: https://github.com/laraxot/module_xot/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Report a bug
      url: https://github.com/laraxot/module_xot/issues/new
      about: Report a reproducable bug
=======
=======
>>>>>>> e61f4ca484 (Squashed 'laravel/Modules/Blog/' content from commit d4b44b78aa)
  - name: Ask a question
    url: https://github.com/:vendor_name/:package_name/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/:vendor_name/:package_name/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/:vendor_name/:package_name/security/policy
    about: Learn how to notify us for sensitive bugs
<<<<<<< HEAD
>>>>>>> ea9b3fa68f (Squashed 'laravel/Modules/Gdpr/' content from commit fbf6cfe9f3)
=======
>>>>>>> e61f4ca484 (Squashed 'laravel/Modules/Blog/' content from commit d4b44b78aa)
=======
    - name: Ask a question
      url: https://github.com/laraxot/module_cms/discussions/new?category=q-a
      about: Ask the community for help
    - name: Request a feature
      url: https://github.com/laraxot/module_cms/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Report a bug
      url: https://github.com/laraxot/module_cms/issues/new
      about: Report a reproducable bug
>>>>>>> c0f6f7d0d3 (Squashed 'laravel/Modules/Cms/' content from commit 8c1c023bf9)
