name: Publish

on:
  push:
    branches:
      - master

<<<<<<< HEAD
permissions:
=======
permissions: 
>>>>>>> c1120baae0 (Squashed 'laravel/Modules/Lang/' content from commit 693742e073)
  contents: write

jobs:
  build:
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c1120baae0 (Squashed 'laravel/Modules/Lang/' content from commit 693742e073)

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Composer
      run: composer install --no-progress --no-suggest

    - name: Node
      run: npm install
<<<<<<< HEAD

    - name: Production
      run: npm run prod

    - name: CNAME
      run: echo "laraxot.github.io/doc_extrafield" > ./build_production/CNAME

    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@latest
      with:
        branch: gh-pages
        folder: build_production
=======
    runs-on: ubuntu-latest

    steps:
      # Step per il checkout del repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step per aggiornare le dipendenze PHP
      - name: Update Dependencies
        run: composer update

      # Step per validare i file composer
      - name: Validate composer.json and composer.lock
        run: composer validate

      # Step per installare le dipendenze PHP
      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      # Step per installare le dipendenze Node.js
      - name: Install Node Dependencies
        run: npm install

      # Step per eseguire la build di produzione
      - name: Build Production Assets
        run: npm run prod

      # Step per impostare il CNAME per GitHub Pages
      - name: Create CNAME File
        run: echo "laraxot.github.io/doc_activity" > ./build_production/CNAME

      # Step per il deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build_production
          clean: true
>>>>>>> a27ba4e75b (Squashed 'laravel/Modules/Activity/' content from commit 05cc09d7b)
=======
      
    - name: Production
      run: npm run prod
      
    - name: CNAME
      run: echo "privacyfed.github.io/doc_extrafield" > ./build_production/CNAME

    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        branch: gh-pages
        folder: build_production
>>>>>>> c1120baae0 (Squashed 'laravel/Modules/Lang/' content from commit 693742e073)
