name: Code Improvement with CodeLlama

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  improve-code:
    name: Improve Code with CodeLlama
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer, php-cs-fixer, phpstan

      # Install dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Install Ollama CLI
      - name: Install Ollama CLI
        run: |
          curl -fsSL https://ollama.ai/install.sh | bash

      # Download and prepare the CodeLlama model
      - name: Download Model
        run: |
          ollama pull llama3

      # Run Ollama for code improvement
      - name: Run llama3 for Code Improvement
        run: |
          echo "Analyze and improve the PHP code in the ./ directory.
          Make it robust, strictly typed, add PHPDoc, integrate Spatie Laravel Data and QueableActions,
          and follow modern PHP best practices. Ensure compatibility with PHP 8.2." | ollama run codellama

      # Run PHP-CS-Fixer for formatting
      #- name: Run PHP-CS-Fixer
      #  run: vendor/bin/php-cs-fixer fix ./ --verbose

      # Run PHPStan for static analysis
      #- name: Run PHPStan
      #  run: vendor/bin/phpstan analyse ./ --level=max

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated code improvements by CodeLlama and GitHub Actions" || echo "No changes to commit"
          git push origin dev
