name: phpinsights
on: [push]

jobs:
    phpinsights:
        runs-on: ubuntu-latest
        name: PHP Insights checks
        steps:
<<<<<<< HEAD
            - uses: actions/checkout@v2
<<<<<<< HEAD
<<<<<<< HEAD
            - uses: shivammathur/setup-php@v2
=======
            - uses: shivammathur/setup-php@latest
>>>>>>> 998733306b (Squashed 'laravel/Modules/Setting/' content from commit 952570add)
=======
            - uses: shivammathur/setup-php@latest
>>>>>>> 8c6e1cc41e (Squashed 'laravel/Modules/User/' content from commit 193294f1c)
=======
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@latest
>>>>>>> b7387cfd6b (Squashed 'laravel/Modules/Notify/' content from commit eb4e12f9e)
              with:
                  php-version: 8.1
            - run: composer install --prefer-dist --no-progress
            - run: composer require nunomaduro/phpinsights --dev
            - run: cp vendor/nunomaduro/phpinsights/stubs/laravel.php phpinsights.php
            - run: vendor/bin/phpinsights -n --ansi --format=github-action --fix
            - uses: stefanzweifel/git-auto-commit-action@latest
              with:
                commit_message: phpinsights
