<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 660b6fffd2 (Squashed 'laravel/Modules/UI/' content from commit b14fdc133)
=======
>>>>>>> ecd8d46956 (Squashed 'laravel/Modules/Gdpr/' content from commit d30cea3b2)
name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
<<<<<<< HEAD
<<<<<<< HEAD
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

=======
name: Static Analysis

on: [push]
>>>>>>> 3f813922dc (Squashed 'laravel/Modules/User/' content from commit edfbd6fa7)
=======
>>>>>>> 660b6fffd2 (Squashed 'laravel/Modules/UI/' content from commit b14fdc133)
=======
>>>>>>> ecd8d46956 (Squashed 'laravel/Modules/Gdpr/' content from commit d30cea3b2)

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        uses: shivammathur/setup-php@v2
=======
        uses: shivammathur/setup-php@latest
>>>>>>> 660b6fffd2 (Squashed 'laravel/Modules/UI/' content from commit b14fdc133)
=======
        uses: shivammathur/setup-php@latest
>>>>>>> ecd8d46956 (Squashed 'laravel/Modules/Gdpr/' content from commit d30cea3b2)
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@latest

<<<<<<< HEAD
<<<<<<< HEAD
      - name: Install Services composer dependencies
        run: cd Services && composer install --no-progress --no-suggest

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
=======
        uses: shivammathur/setup-php@latest
        with:
          php-version: '8.2'
          coverage: none

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan --error-format=github

>>>>>>> 3f813922dc (Squashed 'laravel/Modules/User/' content from commit edfbd6fa7)
=======
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
>>>>>>> 660b6fffd2 (Squashed 'laravel/Modules/UI/' content from commit b14fdc133)
=======
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
>>>>>>> ecd8d46956 (Squashed 'laravel/Modules/Gdpr/' content from commit d30cea3b2)
