name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Validate composer.json and composer.lock
      run: cd docs && composer validate

    - name: Composer
      run: cd docs && composer install --no-progress --no-suggest

    - name: Node
      run: cd docs && npm install

    - name: Production
      run: cd docs && npm run prod

    - name: CNAME
<<<<<<< HEAD
      run: cd docs && echo "laraxot.github.io/module_xot_fila3" > ./build_production/CNAME
=======
      run: cd docs && echo "laraxot.github.io/module_chart" > ./build_production/CNAME
>>>>>>> 998733306b (Squashed 'laravel/Modules/Setting/' content from commit 952570add)

    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@latest
      with:
        branch: gh-pages
        folder: ./docs/build_production
