name: "Update Changelog"

on:
  release:
    types: [released]

<<<<<<< HEAD
<<<<<<< HEAD
=======
permissions:
  contents: write

>>>>>>> 90bf7d5b85 (Squashed 'laravel/Modules/Job/' content from commit d3ea5c83e)
=======
permissions:
  contents: write

>>>>>>> 946fdba366 (Squashed 'laravel/Modules/Notify/' content from commit 6aac1e028)
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v3
=======
        uses: actions/checkout@v4
>>>>>>> 946fdba366 (Squashed 'laravel/Modules/Notify/' content from commit 6aac1e028)
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@latest
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
