name: "Update Changelog"

on:
  release:
    types: [released]

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
permissions:
  contents: write

>>>>>>> 648bc7d47c (Squashed 'laravel/Modules/Job/' content from commit df60037ec)
=======
permissions:
  contents: write

>>>>>>> b7387cfd6b (Squashed 'laravel/Modules/Notify/' content from commit eb4e12f9e)
=======
permissions:
  contents: write

>>>>>>> 88a1f0b933 (Squashed 'laravel/Modules/Tenant/' content from commit ecc88e194)
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/checkout@v3
=======
        uses: actions/checkout@v4
>>>>>>> b7387cfd6b (Squashed 'laravel/Modules/Notify/' content from commit eb4e12f9e)
=======
        uses: actions/checkout@v3
>>>>>>> 88a1f0b933 (Squashed 'laravel/Modules/Tenant/' content from commit ecc88e194)
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@latest
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
